var lang = {
		en:{
			//navigator
			welcome:"Welcome",
			device_cloud:"InHand Cloud",
			cloud_index:"index",
			online_statistic:"online statistic",
			user_manage:"user manage",
			role_manage:"role manage",
			//account
			my_account:"My Account",
			user_name:"user",
			name:"name",
			mobile_phone:"mobile",
			phone:"phone",
			my_role:"role",
			last_login_time:"last login",
			last_logout_time:"last logout",
			last_login_ip:"last IP",
			my_photo:"my photo",
			old_password:"old pwd",
			new_password:"new pwd",
			repeat_password:"repeat pwd",
			//Button
			edit:"edit",
			change_password:"password",
			logout:"logout",
			affirm:"affirm",
			cancel:"cancel",
			add:"add",
			"delete":"delete",
			submit:"submit",
			favor:"favor",
			//Other
			tag:"tag",
			batch:"batch",
			tag_name:"tag name",
			please:"please",
			belongs:"belongs",
			view:"view",
			all:"all",
			//Site
			address:"address",
			ip:"ip",
			business_state:"business state",
			select:"select",
			construction:"construction",
			commissionin:"commissionin",
			fault:"fault",
			overhaul:"overhaul",
			customer:"customer",
			contact_persons:"contact persons",
			email:"email",
			event:"event",
			notice:"notice",
			document:"document",
			detail:"detail",
			site:"site",
			site_name:"site name",
			installation_address:"installation address",
			operation_state:"operation state",
			linkman:"linkman",
			mobile:"mobile",
			
		}
};	